volumes:
  postgres-data:


services:
  odprti-racuni-obcine:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      PYTHONUNBUFFERED: 1
      DJANGO_DEBUG: "yes"
      DJANGO_SETTINGS_MODULE: odprti_racuni_obcine.settings
      DJANGO_SECRET_KEY: make-me-secret
      DJANGO_DATABASE_HOST: db
    volumes:
      - ./:/app

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: odprti_racuni_obcine
      POSTGRES_USER: odprti_racuni_obcine
      POSTGRES_PASSWORD: changeme
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
