# Generated by Django 4.0.5 on 2024-02-27 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obcine", "0029_alter_municipality_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlyexpense",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="obcine.monthlyexpensedocument",
            ),
        ),
        migrations.AlterField(
            model_name="monthlyrevenue",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="obcine.monthlyrevenuedocument",
            ),
        ),
        migrations.AlterField(
            model_name="yearlyexpense",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="obcine.yearlyexpensedocument",
            ),
        ),
        migrations.AlterField(
            model_name="yearlyrevenue",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="obcine.yearlyrevenuedocument",
            ),
        ),
    ]
