# Generated by Django 4.0.5 on 2024-03-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obcine", "0030_alter_monthlyexpense_document_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="municipality",
            name="name_in_rodilnik",
            field=models.TextField(default="", verbose_name="Ime občine v rodilniku"),
            preserve_default=False,
        ),
    ]
