# Generated by Django 4.0.5 on 2024-03-01 10:29

from django.db import migrations

def update_rodilnik(apps, schema_editor):
        Municipality = apps.get_model("obcine", "Municipality")

        for municipality in Municipality.objects.all():
            municipality.name_in_rodilnik = municipality.name
            municipality.save()

class Migration(migrations.Migration):

    dependencies = [
        ('obcine', '0031_municipality_name_in_rodilnik'),
    ]

    operations = [
         migrations.RunPython(update_rodilnik)
    ]
